# Telegram API credentials
api_id: 12345
api_hash: "your_api_hash"

# SQLite database setup
db_name: "messages.db"

# Parameters
limit: null
offset_date: 2025-01-01
reverse: true # true - from offset_date to newest, false - from newest to offset_date

# Channels to scrape
channels:
  - channel_username1
  - channel_username2